**Import Libraries and Datasets**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
amazon_data=pd.read_csv('/content/amazon_cells_labelled.txt',sep='\t',header=None)

In [4]:
amazon_data.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [5]:
#Assign column name
column_name=['Review','Sentiment']
amazon_data.columns=column_name

In [6]:
amazon_data.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [7]:
amazon_data.shape

(1000, 2)

In [8]:
data_imdb=pd.read_csv('/content/imdb_labelled.txt',sep='\t',header=None)

In [9]:
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [10]:
data_imdb.shape

(748, 2)

In [11]:
print(type(data_imdb))

<class 'pandas.core.frame.DataFrame'>


In [12]:
data_imdb.columns=column_name
# amazon_data.columns=column_name


In [13]:
 data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [14]:
data_imdb.shape

(748, 2)

In [15]:
data_yelp=pd.read_csv("/content/yelp_labelled.txt",sep='\t',header=None)

In [16]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [17]:
data_yelp.columns=column_name

In [19]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [20]:
data_yelp.shape

(1000, 2)

In [23]:
data_frame=[data_yelp,data_imdb,amazon_data]

In [24]:
data=pd.concat(data_frame)

In [25]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [26]:
data.shape

(2748, 2)

In [27]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [28]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [63]:
x=data['Review']
y=data['Sentiment']

**Data cleaning**

here we will remove stopwords, punctuations
as well as we will apply lemmatization

In [29]:
import string

In [30]:
puntch=string.punctuation

In [31]:
puntch

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

ERROR: Could not find a version that satisfies the requirement specy (from versions: none)
ERROR: No matching distribution found for specy


In [34]:
from spacy.lang.en.stop_words import STOP_WORDS

In [35]:
stopwords=list(STOP_WORDS)

In [36]:
stopwords

['forty',
 'three',
 'often',
 'upon',
 'other',
 'should',
 'can',
 'doing',
 'third',
 '‘ve',
 'hereupon',
 'seeming',
 'noone',
 'nevertheless',
 'the',
 'however',
 'then',
 'on',
 "'re",
 'becoming',
 'same',
 'otherwise',
 'mine',
 'thereby',
 'him',
 'during',
 'because',
 'must',
 "'d",
 'his',
 'again',
 'besides',
 'after',
 'or',
 'how',
 'former',
 'along',
 'through',
 '’ll',
 'everywhere',
 'they',
 'hence',
 'myself',
 'around',
 'now',
 'even',
 'something',
 'below',
 'just',
 'whither',
 'latterly',
 "'ve",
 'for',
 'due',
 'neither',
 'side',
 'that',
 'am',
 'our',
 'became',
 'afterwards',
 'ten',
 'thus',
 'so',
 'its',
 'well',
 'hers',
 'ourselves',
 'also',
 'everyone',
 'seemed',
 'when',
 'were',
 'a',
 'me',
 'and',
 'whereafter',
 'unless',
 "'ll",
 'very',
 'hereby',
 'whoever',
 'some',
 'i',
 'others',
 'sometime',
 'any',
 'thence',
 'out',
 'beforehand',
 'whose',
 'using',
 'thereafter',
 'mostly',
 'moreover',
 'many',
 'whatever',
 'about',
 'no',
 

In [37]:
import spacy

In [38]:
nlp=spacy.load('en_core_web_sm')

In [49]:
def text_data_cleaning(sentance):
  doc=nlp(sentance)

  token=[]
  for i in doc:
    if i.lemma_!='-PRON-':
      temp=i.lemma_.lower().strip()
    else:
      temp=i.lemma_.lower_
    token.append(temp)

  cleand_token=[]
  for i in token:
    if i not in stopwords and i not in puntch:
      cleand_token.append(i)
  return cleand_token


if root form of that word is not pronoun then it is going to convert that into lower form and if that word is a proper noun, then we are directly taking lower form, because there is no lemma for proper noun

In [51]:
text_data_cleaning("if root form of that word is not pronoun then it is going to convert ")

['root', 'form', 'word', 'pronoun', 'convert']

**Vectorization Feature Engineering**

In [56]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [58]:
tfidf=TfidfVectorizer(tokenizer=text_data_cleaning)

In [60]:
classifier=LinearSVC()

**Train the Model**

In [61]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=4)

In [65]:
x_train.shape,x_test.shape

((1923,), (825,))

In [66]:
x_train.head()

46     I love Lane, but I've never seen her in a movi...
810    The server was very negligent of our needs and...
201         All in all I think it was a good investment.
443    It's a campy sort of film that's a joy to watc...
287    This movie was kind of long in length, but I e...
Name: Review, dtype: object

**Fit the x_train and y_train**

In [67]:
clf=Pipeline([("tfidf",tfidf),('clf',classifier)])

In [68]:
clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x78dba7d7e3b0>)),
                ('clf', LinearSVC())])

**Predict the model**

In [70]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [72]:
y_pred=clf.predict(x_test)

In [73]:
confusion_matrix(y_pred,y_test)

array([[318, 106],
       [ 83, 318]])

In [75]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.79      0.75      0.77       424
           1       0.75      0.79      0.77       401

    accuracy                           0.77       825
   macro avg       0.77      0.77      0.77       825
weighted avg       0.77      0.77      0.77       825



In [76]:
accuracy_score(y_pred,y_test)

0.7709090909090909

In [78]:
clf.predict(["Not sure who was more lost - the flat characte"])

array([0])

In [80]:
clf.predict(["The selection on the menu was great"])

array([1])